### ISSUE TITLE
Spatial index

### ISSUE THREAD

**Issue by lindsejs** [mrumkovskis/addresses#4]
Hi Addresses Team,

is it possible to add a spatial index, e.g., if I provide the coordinate in a request, return matched addresses ordered by the closest distance:

/address?search=sala&type=106&coord=363128;576876

**Comment by lindsejs** [comment]
Maybe without address search, just closest to coordinates:
/address?geosearch=363128;576876

**Comment by mrumkovskis** [comment]
Implemented. For example:
/address?x=506220.304&y=313143.387&limit=10
